name: project_ishi
description: Project Ishi is an application for doctors to track different patient and procedure related information.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Persistence
  sembast: ^3.0.2
  shared_preferences: ^2.0.5
  # Design Pattern
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  # Misc
  uuid: ^3.0.4
  excel: ^2.0.0-null-safety-3
  # UI
  font_awesome_flutter: ^9.0.0
  # Custom Packages
  auth_repo:
    path: packages/auth_repo

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/labcoat/
    - assets/8_bit_heart.png