name: Test
on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup environment for Flutter (Beta)
        uses: subosito/flutter-action@v1
        with:
          channel: beta
      
      - name: Get all packages
        run: flutter pub get
      
      - name: Unit Test Package `auth_repo`
        run: flutter test --concurrency=1 ./packages/auth_repo/

      - name: Unit Test Package `database_repo`
        run: flutter test --concurrency=1 ./packages/database_repo/